### PR TITLE
Version 0.8.1

### LINKED ISSUE #75: Plugins install on wrong PATH when VAGRANT_HOME is set to another location than homedir
Hi,

I've set a different VAGRANT_HOME to "D:\WORK\\.vagrant.d" (for example), but, when I am using the vagrant_plugin resource, everything is still installed on C:\Users\#{username}\\.vagrant.d

Please modify the following code to not overwrite the PATH if VAGRANT_HOME is already set and is different than homedir/.vagrant.d

```
    def vagrant_home
      user_home_dir = home_dir
      ::File.join(user_home_dir, '.vagrant.d') unless user_home_dir.nil?
    end

    def home_dir
      return Dir.home unless username

      # Dir.home(user) raises ArgumentError: user `user` doesn't exist
      # on Windows so we must workaround for now.
      if windows?
        "C:/Users/#{username}" if Dir.exist?("C:/Users/#{username}")
      else
        begin
          Dir.home(username)
        rescue ArgumentError
          raise UserNotFoundError
        end
      end
    end
```

### PR DESCRIPTION
**Pull request by MarkGibbons**
Use ENV VAGRANT_HOME as the location to install vagrant plugins. Resolves #75.

### CODE REVIEW

File: metadata.rb [hunk 1]
```diff
@@ -13,15 +13,15 @@
...
+maintainer_email 'help@sous-chefs.org'
 license          'Apache-2.0'
 description      'Installs Vagrant and provides a vagrant_plugin LWRP for installing Vagrant plugins.'
 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
-version          '0.8.0'
+version          '0.8.1'
 
-source_url       'https://github.com/sous-chefs/vagrant-cookbook' if respond_to?(:source_url)
-issues_url       'https://github.com/sous-chefs/vagrant-cookbook/issues' if respond_to?(:issues_url)
+source_url       'https://github.com/sous-chefs/vagrant' if respond_to?(:source_url)
```
Comment (tas50) [inline metadata.rb]: respond_to can go away. That's a Chef 11 thing

File: providers/plugin.rb [hunk 2]
```diff
@@ -14,7 +14,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-use_inline_resources if defined?(:use_inline_resources)
+use_inline_resources if defined?(:use_inline_resources) # ~FC113
```
Comment (tas50) [inline providers/plugin.rb]: We can just set use_inline_resources. Checking if it's defined is a Chef 11 thing
