### PR TITLE
Convert the resources to custom resources

### LINKED ISSUE #101: Installing plugin vagrant-libvirt fails on ubuntu 18.04
### Cookbook version
0.9.1

### Chef-client version
14.10.9

### Platform Details
ubuntu 18.04.2

### Scenario:
Installation of the vagrant-libvirt plugin like described in #100 fails (see output below). Installing it as the actual user running the same command as used by the ` shell_out` works as expected.

```
[2019-03-22T11:20:22+00:00] ERROR: Mixlib::ShellOut::ShellCommandFailed: vagrant_plugin[vagrant-libvirt] (vagrant::install_plugins line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of vagrant plugin install vagrant-libvirt ----
STDOUT: Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
STDERR: Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /home/ingo/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1/ext/libvirt
/opt/vagrant/embedded/bin/ruby -r ./siteconf20190322-24410-h69yh1.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ingo/.vagrant.d/gems/2.4.4/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ingo/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/ingo/.vagrant.d/gems/2.4.4/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/gem_make.out
---- End output of vagrant plugin install vagrant-libvirt ----
Ran vagrant plugin install vagrant-libvirt returned 1

```

### PR DESCRIPTION
**Pull request by MarkGibbons**
Add a env property to the plugin resource to allow for setting environment variables.
Add and example of installing the vagrant-libvirt plugin, this plugin requires
specific environment variable settings. See https://github.com/vagrant-libvirt/vagrant-libvirt/issues/891

## Description

Update the cookbook to use custom resources.
Add an env property to the plugin resource.
Add examples in the tests for using the env property.
Remove the chef 13 tests and instances. Use chef 14 as the base install.

### Issues Resolved

#101

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x ] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by MarkGibbons** [comment]
This PR addresses issue #101.

File: test/integration/linux_chef14/inspec/vagrant_spec.rb [hunk 1]
```diff
@@ -1,13 +1,27 @@
...
+  its('exit_status') { should eq 0 }
+end
+
+if os[:family] == 'debian'
+  describe command('vagrant plugin list') do
+    its('stdout') { should match(/vagrant-libvirt/) }
+  end
+end
+
 if os[:family] == 'windows'
```
[the remark this answers is not in the document]
Comment (MarkGibbons) [reply test/integration/linux_chef14/inspec/vagrant_spec.rb]: Deleted.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: README.md [hunk 2]
```diff
@@ -123,6 +128,9 @@ vagrant_plugin 'vagrant-berkshelf'
 end
 
 # Install the plugins as the `donuts` user, into ~/donuts/.vagrant.d
+# .vagrant.d will be allocated if it does not exist.
+# If a specific user, group or mode is desired use a directory resource to
+# create the .vagrant.d directory.
 vagrant_plugin 'vagrant-aws'
```
Comment (qubitrenegade) [inline README.md]: Should this be `vagrant_plugin 'vagrant-aws' do` ?

File: README.md [hunk 3]
```diff
@@ -133,13 +141,16 @@ vagrant_plugin 'vagrant-winrm' do
   user node['vagrant']['user']
   password node['vagrant']['password']
 end
+
+# Install a plugin in the /root directory
+vagrant_plugin 'vagrant-aws'
```
Comment (qubitrenegade) [inline README.md]: Should this be `vagrant_plugin 'vagrant-aws' do` ?

File: README.md [hunk 4]
```diff
@@ -177,6 +188,11 @@ running `rbenv rehash`. Likewise, if you have multiple copies of the
 vagrant gem installed, you'll need to clean up all versions. This
 recipe won't support such craziness :-).
 
+# Notes about specific plugins
+*  vagrant-libvirt. Installing this plugin has required setting environment
+variables on ubuntu system. Adding env CONFIGURE_ARGS: 'with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib'
+to the vagrant_plugin resource properties has worked.
+
```
Comment (qubitrenegade) [inline README.md]: Does it make sense to add an usage example?

It wasn't clear without reading the resource that `env` is the property, I _think_ this is intended usage?

```
vagrant_plugin 'vagrant-aws' do
  user 'donuts'
  env CONFIGURE_ARGS: 'with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib'
  action :install
end
```

Is this always going to be the same on Ubuntu?  Are there scenarios where this is not required on Ubuntu?

Would it make sense instead of adding this as a property have a constant?  Or to make it easier on users set the default for ubuntu, maybe something to the effect of:

```
# resources/plugin.rb
property :env, [Hash, nil], default: lazy {
  if platform?('ubuntu')
    CONFIGURE_ARGS: 'with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib'
  else
    nil
  end
}
```

I think it's ok as-is, but this seems like a property that most people won't want to know about unless they need to know about it.

File: README.md (hunk 2 above)
Comment (MarkGibbons) [reply README.md]: Duh. thanks

File: README.md (hunk 4 above)
Comment (MarkGibbons) [reply README.md]: The env property settings in the discussion only apply to the vagrant-libvirt plugin. Those aren't general ubuntu settings.  Someone installing that plugin also has to install the package prereqs.  I don't want to or know how to maintain a table of the prereqs for each plugin.  If we needed something for all the plugins for ubuntu I'd do somthing like you suggest.

**Comment by MarkGibbons** [comment]
@qubitrenegade  Thanks for looking at it.  Rewriting to use custom resources sometimes makes for a big pull request.

File: README.md (hunk 4 above)
Comment (qubitrenegade) [reply README.md]: Gotcha!  Ok, that was the piece I was missing, this is specifically for `vagrant-libvirt`.

Totally makes sense, I think that's reasonable.

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,5 +1,13 @@
 # Vagrant Cookbook Changelog
 
+## 0.10.0
```
Comment (Xorima) [inline CHANGELOG.md]: I feel like this should be a 1.0.0 release?

File: TESTING.md [hunk 6]
```diff
@@ -1,32 +1,13 @@
...
-
-```
-rake foodcritic            # Lint Chef cookbooks
-rake rubocop               # Run RuboCop
-rake rubocop:auto_correct  # Auto-correct RuboCop offenses
-rake spec                  # Run RSpec code examples
-rake style                 # Run Rubocop and Foodcritic style checks
-rake test                  # Run style checks and unit tests
-```
+This cookbook follows the guidelines for chefstyle. Run chefstyle -a to find and auto correct style problems.
```
Comment (Xorima) [inline TESTING.md]: Isn't it cookstyle?

Comment (MarkGibbons) [reply TESTING.md]: Cookstyle - yes.

**Comment by damacus** [comment]
@MarkGibbons looks great. What do we need to get this finished off? Looks pretty close

**Comment by MarkGibbons** [comment]
Rebase and push.  Probably early next week..

**Comment by MarkGibbons** [comment]
Rebased and fixed the suggestions.  Waiting for a review.

**Comment by MarkGibbons** [comment]
Resolves #101. One of the tests shows the exact syntax needed.
